server:
  port: 8083
  tomcat:
    max-threads: 300

spring:
  application:
    name: artexperience-api
  data:
    rest:
      default-page-size: 40
      max-page-size: 1000
      default-media-type: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/artexperiencedb
    username: postgres
    password: postgres
#    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/znflcgpt
#    username: znflcgpt
#    password: FdN1_UUcNthaEXwYGc93F-3sJPmkd1ov
#    url: jdbc:postgresql://ec2-3-208-50-226.compute-1.amazonaws.com/df6fhohpf8uu3
#    username: sxutyfndujrygn
#    password: 2f632044e43443185757006a153c4173a66bdb89f59398194361e54285b76646
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

