server:
  port: 8083
  tomcat:
    max-threads: 300

spring:
  application:
    name: artexperience-api
  data:
    rest:
      default-page-size: 40
      max-page-size: 1000
      default-media-type: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
#   Local DB Connections
#    url: jdbc:postgresql://localhost:5432/artexperiencedb
#    username: postgres
#    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: zerobyone
    password: postgres

#    Production DB Connections
#    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/znflcgpt
#    username: znflcgpt
#    password: FdN1_UUcNthaEXwYGc93F-3sJPmkd1ov
#    url: jdbc:postgresql://ec2-34-238-26-109.compute-1.amazonaws.com/d460qlba6iot8u
#    username: fjlzvntraxkgzh
#    password: 382376eea897c0f155377e79cd1cf8f38fb08c0df268f1f55ad9a1a7229170e7
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

reports-reserves:
  scheduler:
    enabled: true
    cron: 0 3 * * * *

mail:
  username: art.experience.uy.2020@gmail.com
  password: art_experience_2020
  to: damianezetiel1@gmail.com, mitsuki-kun@hotmail.com #peraltana.21@gmail.com,max3.1994@gmail.com,smtp.test.zero@gmail.com,
  host: smtp.gmail.com #host
  port: 587
  auth: true
  enable: true
  required: true
  content:
    subject: "Confirmación de Reserva" #subject-email
    description:  "Hola [USERNAME], \n\n Gracias por formar parte de Art Experience :rocket: \n Su reserva ah sido agendada correctamente!! \n\nDetalle de la Reserva: \n "#content-text of email